# Generated by Django 3.2.3 on 2021-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('price', models.IntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('display_picture', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
