# Generated by Django 3.2.3 on 2021-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='technologies',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='price',
            field=models.IntegerField(default=True, max_length=50),
        ),
    ]
