# Generated by Django 3.2.3 on 2021-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_maker', '0002_auto_20210719_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='display_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
