# Generated by Django 3.2.3 on 2021-07-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_maker', '0003_auto_20210719_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile_maker.user_profile')),
            ],
        ),
    ]
