# Generated by Django 3.2.3 on 2021-07-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_maker', '0004_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
