# Generated by Django 3.2.3 on 2021-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=10000000),
        ),
    ]
