# Generated by Django 3.2.3 on 2021-08-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0002_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
