# Generated by Django 3.2.2 on 2021-06-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0004_listing_explain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
