# Generated by Django 3.2.2 on 2021-07-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
