# Generated by Django 3.2.2 on 2021-07-19 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0008_auto_20210719_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 3, 8, 11, 414236, tzinfo=utc), null=True),
        ),
    ]
