# Generated by Django 3.2.3 on 2021-07-19 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0011_auto_20210719_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 11, 28, 49, 997876, tzinfo=utc), null=True),
        ),
    ]
