# Generated by Django 3.2.3 on 2021-07-20 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0020_auto_20210720_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='display_picture',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 3, 57, 58, 579330, tzinfo=utc), null=True),
        ),
    ]
