# Generated by Django 3.2.2 on 2021-07-22 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0022_auto_20210722_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 9, 16, 17, 237863, tzinfo=utc), null=True),
        ),
    ]
