# Generated by Django 3.2.3 on 2021-07-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0021_auto_20210720_1257'),
        ('crystal', '0022_auto_20210722_1732'),
    ]

    operations = [
    ]
