# Generated by Django 3.2.2 on 2021-07-22 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0023_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='explain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 10, 33, 0, 3112, tzinfo=utc), null=True),
        ),
    ]
