# Generated by Django 3.2.3 on 2021-07-26 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0023_merge_0021_auto_20210720_1257_0022_auto_20210722_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='display_picture',
        ),
        migrations.AlterField(
            model_name='bid',
            name='highest_bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 15, 17, 10, 130654, tzinfo=utc), null=True),
        ),
    ]
