# Generated by Django 3.2.2 on 2021-07-22 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0024_auto_20210722_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='explain',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 10, 35, 49, 893559, tzinfo=utc), null=True),
        ),
    ]
