# Generated by Django 3.2.2 on 2021-07-22 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0025_auto_20210722_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='explain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 10, 39, 34, 740544, tzinfo=utc), null=True),
        ),
    ]
