# Generated by Django 3.2.3 on 2021-08-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0024_auto_20210727_0017'),
        ('crystal', '0026_auto_20210722_1939'),
    ]

    operations = [
    ]
