# Generated by Django 3.2.3 on 2021-08-05 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0028_auto_20210805_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
        migrations.AddField(
            model_name='bid',
            name='time_ending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='time_starting',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='time_starting',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 11, 0, 4, 872193, tzinfo=utc), null=True),
        ),
    ]
