# Generated by Django 3.2.3 on 2021-08-05 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0029_auto_20210805_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time_ending',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='time_starting',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='listing',
            name='time_ending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 11, 31, 48, 89500, tzinfo=utc), null=True),
        ),
    ]
