# Generated by Django 3.2.3 on 2021-08-05 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0030_auto_20210805_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time_ending',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='time_starting',
        ),
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 15, 28, 50, 266713, tzinfo=utc), null=True),
        ),
    ]
