# Generated by Django 3.2.3 on 2021-08-05 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0035_auto_20210806_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 15, 53, 9, 795013, tzinfo=utc), null=True),
        ),
    ]
