# Generated by Django 3.2.2 on 2021-08-07 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0038_auto_20210807_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_ending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 3, 20, 19, 275206, tzinfo=utc), null=True),
        ),
    ]
