# Generated by Django 3.2.2 on 2021-08-07 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0041_auto_20210807_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_ending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 3, 43, 15, 694083, tzinfo=utc), null=True),
        ),
    ]
