# Generated by Django 3.2.2 on 2021-08-07 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0043_auto_20210807_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_starting',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time_ending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 7, 23, 8, 990843, tzinfo=utc), null=True),
        ),
    ]
