# Generated by Django 3.2.3 on 2021-08-07 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0043_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time_starting',
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 5, 18, 22, 338519, tzinfo=utc), null=True),
        ),
    ]
