# Generated by Django 3.2.3 on 2021-08-07 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0044_auto_20210807_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 6, 55, 47, 929374, tzinfo=utc), null=True),
        ),
    ]
